[project]
name = "mbta-gtfs-sqlite"
version = "1.2.0"
description = "Query the MBTA's static GTFS feeds using sqlite"
authors = [{ name = "Ian Reynolds", email = "ireynolds@transitmatters.info" }]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "requests>=2.32.5,<3",
    "SQLAlchemy>=2.0.43,<3",
    "more-itertools>=10.8.0,<12",
]

[tool.poetry]
packages = [{ include = "mbta_gtfs_sqlite" }]

[tool.poetry.group.dev.dependencies]
black = "^25.9.0"
memray = "^1.19.0"

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
